---
source: Rmd
title: "Importing and annotating quantified data into R"
teaching: XX
exercises: XX
questions:
- "How do we get our data into R?"
objectives:
- "Learn how to import the quantifications into a SummarizedExperiment object."
- "Learn how to add additional gene annotations to the object."
keypoints:
- "Key point 1"
---

```{r, echo=FALSE, purl=FALSE, message=FALSE}
source("download_data.R")
```

```{r, include=FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("04-")
```

# Read the data

## Counts

```{r}
counts <- read.csv("data/GSE96870_counts_cerebellum.csv", 
                   row.names = 1)
```

## Sample annotations

```{r}
coldata <- read.csv("data/GSE96870_coldata_cerebellum.csv",
                    row.names = 1)
```

## Gene annotations

Need to be careful - the descriptions contain both commas and ' (e.g., 5')

```{r}
rowdata <- read.delim("data/GSE96870_rowdata.tsv", sep = "\t", 
                      header = TRUE, quote = "",
                      row.names = 1)
```

Mention other ways of getting annotations, and practice querying org package.
Important to use the right annotation source/version. 

```{r}
suppressPackageStartupMessages({
    library(org.Mm.eg.db)
})
mapIds(org.Mm.eg.db, keys = "497097", column = "SYMBOL", keytype = "ENTREZID")
```

Check feature types

```{r}
table(rowdata$gbkey)
```


# Assemble SummarizedExperiment

```{r}
stopifnot(rownames(rowdata) == rownames(counts),
          rownames(coldata) == colnames(counts))

se <- SummarizedExperiment(
    assays = list(counts = as.matrix(counts)),
    rowData = rowdata,
    colData = coldata
)
```

# Save SummarizedExperiment

```{r}
saveRDS(se, "data/GSE96870_se.rds")
```

# Session info

```{r}
sessionInfo()
```
