---
source: Rmd
title: RStudio Project and Experimental Data
teaching: XX
exercises: XX
---

:::::::::::::::::::::::::::::::::::::: questions 

- How do you use RStudio project to manage your analysis project?
- What is the most effective way for organising directories for an analysis project?
- How to download a data set from Gene Expression Omnibus (GEO)?

::::::::::::::::::::::::::::::::::::::::::::::::

::::::::::::::::::::::::::::::::::::: objectives

- Create an RStudio project and the necessary directories for carrying out an analysis.
- Download the data set that will be used for the subsequent episodes.

::::::::::::::::::::::::::::::::::::::::::::::::

## What is RStudio project?

In this lesson, we will be using RStudio, a free integrated development environment (IDE),
to assist us in developing the R code necessary for analysing a RNAseq data.
Importantly, we will leverage RStudio projects, a feature built-in to RStudio for managing our analysis project.

:::::::::::::::::::::::::::::::::::::::  prereq

## Navigating RStudio
If you require assistance with RStudio or its general usage, please refer to our
[Introduction to data analysis with R and Bioconductor](https://carpentries-incubator.github.io/bioc-intro/20-r-rstudio.html)
lesson.

:::::::::::::::::::::::::::::::::::::::


## Download data

The data we will use in this lesson is obtained from the [Gene Expression Omnibus](https://www.ncbi.nlm.nih.gov/geo/), accession number [GSE96870](https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE96870).

```{r}
dir.create("data", showWarnings = FALSE)
download.file(
    url = "https://github.com/carpentries-incubator/bioc-rnaseq/raw/main/episodes/data/GSE96870_counts_cerebellum.csv", 
    destfile = "data/GSE96870_counts_cerebellum.csv"
)

download.file(
    url = "https://github.com/carpentries-incubator/bioc-rnaseq/raw/main/episodes/data/GSE96870_coldata_cerebellum.csv?raw=true", 
    destfile = "data/GSE96870_coldata_cerebellum.csv"
)

download.file(
    url = "https://github.com/carpentries-incubator/bioc-rnaseq/raw/main/episodes/data/GSE96870_coldata_all.csv?raw=true", 
    destfile = "data/GSE96870_coldata_all.csv"
)

download.file(
    url = "https://github.com/carpentries-incubator/bioc-rnaseq/raw/main/episodes/data/GSE96870_rowranges.tsv?raw=true", 
    destfile = "data/GSE96870_rowranges.tsv"
)
```


::::::::::::::::::::::::::::::::::::: keypoints 

- When starting to use a new Bioconductor package, it is often good practice to go through the accompanying vignette and test some of the commands on the provided example data, before applying it to one's own data.

::::::::::::::::::::::::::::::::::::::::::::::::

