---
source: Rmd
title: "Experimental design"
teaching: XX
exercises: XX
questions:
- "How do we design experiments optimally?"
- "How do we interpret a given design?"
objectives:
- "Explain the formula notation and design matrices."
- "Explore different designs and learn how to interpret coefficients."
keypoints:
- "Key point 1"
editor_options: 
  chunk_output_type: console
---

```{r, include=FALSE}
source("../bin/chunk-options.R")
knitr_fig_path("03-")
options(width = 120)
```

```{r}
suppressPackageStartupMessages({
    library(SummarizedExperiment)
    library(ExploreModelMatrix)
    library(dplyr)
})
```

```{r}
se <- readRDS(gzcon(url("https://github.com/Bioconductor/bioconductor-teaching/blob/master/data/GSE96870/GSE96870_se.rds?raw=true")))
meta <- as.data.frame(colData(se))
meta
```

```{r}
vd <- VisualizeDesign(sampleData = meta, 
                      designFormula = ~ tissue + time + sex)
vd$cooccurrenceplots
```

# Simple example - compare males and females, non-infected spinal cord

```{r}
meta_noninf_spc <- meta %>% filter(time == "Day 0" & 
                                       tissue == "Spinal cord")
meta_noninf_spc
vd <- VisualizeDesign(sampleData = meta_noninf_spc, 
                      designFormula = ~ sex)
vd$designmatrix
vd$plotlist
```

> ## Challenge: Can you do it?
>
> Set up the design formula to compare the three time points (Day 0, Day 4, Day 8) in the male spinal cord samples, and visualize it using `ExploreModelMatrix`. 
>
>
> > ## Solution
> >
> > ```{r, echo=TRUE}
> > meta_male_spc <- meta %>% filter(sex == "Male" & tissue == "Spinal cord")
> > meta_male_spc
> > vd <- VisualizeDesign(sampleData = meta_male_spc, designFormula = ~ time)
> > vd$designmatrix
> > vd$plotlist
> > ```
> {: .solution}
{: .challenge}

# Factorial design without interactions

```{r}
meta_noninf <- meta %>% filter(time == "Day 0")
meta_noninf
vd <- VisualizeDesign(sampleData = meta_noninf, 
                      designFormula = ~ sex + tissue)
vd$designmatrix
vd$plotlist
```

# Factorial design with interactions

```{r}
meta_noninf <- meta %>% filter(time == "Day 0")
meta_noninf
vd <- VisualizeDesign(sampleData = meta_noninf, 
                      designFormula = ~ sex * tissue)
vd$designmatrix
vd$plotlist
```
